### ISSUE TITLE
WOrst Team 

### ISSUE THREAD

**Issue by Spain2394** [piepieninja/Robotics_Project_02#1]
Particle filter is too slow, you won't be able to keep up with kUKA!

**Comment by caadkins** [comment]
Hello Spain2394, we're so glad to hear from users like you! We would like to remind you that the particle filter is actually being implemented by one of the other teams competing in this event. While we encourage constructive criticism from any and all sources, we do ask that you do your research before spreading false information about our team. We take pride in our work and have high expectations for our PR2 robot. Best of luck to you and your team trying to keep with us!

Sincerely,
There can be only one Team-C

**Comment by piepieninja** [comment]
closing issue because @Spain2394 is a dumb idiot
